version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore_cache:
          key: worksheet-dependency-cache-v1-{{ checksum "worksheet/package.json" }}
      - run:
          name: Install worksheet dependencies
          command: |
            cd worksheet
            npm install
      - save_cache:
          key: worksheet-dependency-cache-v1-{{ checksum "worksheet/package.json" }}
          paths:
            - worksheet/node_modules
      - run:
          name: Build worksheet
          command: |
            cd worksheet
            npm run build
