version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: worksheet-dependency-cache-v1-{{ checksum "worksheet/ts/package.json" }}
      - run:
          name: Install worksheet dependencies
          command: |
            cd worksheet/ts
            npm install
      - save_cache:
          key: worksheet-dependency-cache-v1-{{ checksum "worksheet/ts/package.json" }}
          paths:
            - worksheet/ts/node_modules
      - run:
          name: Build worksheet
          command: |
            cd worksheet/ts
            npm run build
