version: '2'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
        - "127.0.0.1:27017:27017"
        volumes:
        - /var/lib/dressdiscover/data/mongo:/data/db
        - /var/log:/var/log
        command: mongod --storageEngine wiredTiger --wiredTigerCacheSizeGB 2 --dbpath /data/db
