version: "3"
services:
  core-service:
    build:
      context: service/core
    container_name: core-service
    stdin_open: true
  fuseki:
    container_name: fuseki
    environment:
      ADMIN_PASSWORD: xWJwxehQADhT
      ENABLE_DATA_WRITE: "true"
      ENABLE_UPDATE: "true"
      ENABLE_UPLOAD: "true"
    image: secoresearch/fuseki
    ports:
      - 127.0.0.1:3030:3030
    volumes:
      - fuseki-databases:/fuseki-base/databases/
volumes:
  fuseki-databases:
