from .costume_core_predicate import CostumeCorePredicate

ICOMtype = CostumeCorePredicate(display_name_en='ICOM type', id='ICOMtype', uri='https://w3id.org/costumeCore/ontology/ICOMtype')
accessoryType = CostumeCorePredicate(display_name_en='accessory type', id='accessoryType', uri='https://w3id.org/costumeCore/ontology/accessoryType')
alternative = CostumeCorePredicate(display_name_en='alternative title', id='alternative', uri='http://purl.org/dc/terms/alternative')
cataloguerWithDate = CostumeCorePredicate(display_name_en='cataloguer with date', id='cataloguerWithDate', uri='https://w3id.org/costumeCore/ontology/cataloguerWithDate')
cbLengthIn = CostumeCorePredicate(display_name_en='center back length', id='cbLengthIn', uri='https://w3id.org/costumeCore/ontology/cbLengthIn')
cfLengthIn = CostumeCorePredicate(display_name_en='center front length', id='cfLengthIn', uri='https://w3id.org/costumeCore/ontology/cfLengthIn')
chestIn = CostumeCorePredicate(display_name_en='chest', id='chestIn', uri='https://w3id.org/costumeCore/ontology/chestIn')
classification = CostumeCorePredicate(display_name_en='classification', id='classification', uri='https://w3id.org/costumeCore/ontology/classification')
closure = CostumeCorePredicate(display_name_en='closure', id='closure', uri='https://w3id.org/costumeCore/ontology/closure')
closurePlacement = CostumeCorePredicate(display_name_en='closure placement', id='closurePlacement', uri='https://w3id.org/costumeCore/ontology/closurePlacement')
coatType = CostumeCorePredicate(display_name_en='coat type', id='coatType', uri='https://w3id.org/costumeCore/ontology/coatType')
collar = CostumeCorePredicate(display_name_en='collar', id='collar', uri='https://w3id.org/costumeCore/ontology/collar')
colorMain = CostumeCorePredicate(display_name_en='color main', id='colorMain', uri='https://w3id.org/costumeCore/ontology/colorMain')
colorSecondary = CostumeCorePredicate(display_name_en='color secondary', id='colorSecondary', uri='https://w3id.org/costumeCore/ontology/colorSecondary')
condition = CostumeCorePredicate(display_name_en='condition', id='condition', uri='https://w3id.org/costumeCore/ontology/condition')
conditionDescription = CostumeCorePredicate(display_name_en='condition description', id='conditionDescription', uri='https://w3id.org/costumeCore/ontology/conditionDescription')
costOriginal = CostumeCorePredicate(display_name_en='cost original', id='costOriginal', uri='https://w3id.org/costumeCore/ontology/costOriginal')
costumeComponents = CostumeCorePredicate(display_name_en='costume components', id='costumeComponents', uri='https://w3id.org/costumeCore/ontology/costumeComponents')
creator = CostumeCorePredicate(display_name_en='creator', id='creator', uri='http://purl.org/dc/terms/creator')
culturalContext = CostumeCorePredicate(display_name_en='cultural context', id='culturalContext', uri='http://purl.org/vra/culturalContext')
date = CostumeCorePredicate(display_name_en='date', id='date', uri='http://purl.org/dc/terms/date')
description = CostumeCorePredicate(display_name_en='description', id='description', uri='http://purl.org/dc/terms/description')
dimensionsOther = CostumeCorePredicate(display_name_en='measurements other', id='dimensionsOther', uri='https://w3id.org/costumeCore/ontology/dimensionsOther')
donator = CostumeCorePredicate(display_name_en='donor', id='donator', uri='http://purl.org/vra/donator')
dressType = CostumeCorePredicate(display_name_en='dress type', id='dressType', uri='https://w3id.org/costumeCore/ontology/dressType')
endDate = CostumeCorePredicate(display_name_en='date latest', id='endDate', uri='http://purl.org/vra/endDate')
exhibitions = CostumeCorePredicate(display_name_en='exhibitions', id='exhibitions', uri='https://w3id.org/costumeCore/ontology/exhibitions')
extent = CostumeCorePredicate(display_name_en='extent', id='extent', uri='http://purl.org/dc/terms/extent')
fiber = CostumeCorePredicate(display_name_en='fiber', id='fiber', uri='https://w3id.org/costumeCore/ontology/fiber')
function = CostumeCorePredicate(display_name_en='function', id='function', uri='https://w3id.org/costumeCore/ontology/function')
gender = CostumeCorePredicate(display_name_en='gender', id='gender', uri='https://w3id.org/costumeCore/ontology/gender')
hasInscription = CostumeCorePredicate(display_name_en='label', id='hasInscription', uri='http://purl.org/vra/hasInscription')
hasTechnique = CostumeCorePredicate(display_name_en='technique', id='hasTechnique', uri='http://purl.org/vra/hasTechnique')
hemCircumferenceIn = CostumeCorePredicate(display_name_en='hem circumference', id='hemCircumferenceIn', uri='https://w3id.org/costumeCore/ontology/hemCircumference')
hipsIn = CostumeCorePredicate(display_name_en='hips', id='hipsIn', uri='https://w3id.org/costumeCore/ontology/hipsIn')
identifier = CostumeCorePredicate(display_name_en='identifier', id='identifier', uri='http://purl.org/dc/terms/identifier')
isReferencedBy = CostumeCorePredicate(display_name_en='references', id='isReferencedBy', uri='http://purl.org/dc/terms/isReferencedBy')
jacketType = CostumeCorePredicate(display_name_en='jacket type', id='jacketType', uri='https://w3id.org/costumeCore/ontology/jacketType')
length = CostumeCorePredicate(display_name_en='length', id='length', uri='https://w3id.org/costumeCore/ontology/skirtLength')
lifeStages = CostumeCorePredicate(display_name_en='life stages', id='lifeStages', uri='https://w3id.org/costumeCore/ontology/lifeStages')
liturgicalType = CostumeCorePredicate(display_name_en='liturgical type', id='liturgicalType', uri='https://w3id.org/costumeCore/ontology/liturgicalType')
mannequin = CostumeCorePredicate(display_name_en='mannequin', id='mannequin', uri='https://w3id.org/costumeCore/ontology/mannequin')
material = CostumeCorePredicate(display_name_en='material', id='material', uri='http://purl.org/vra/material')
neckline = CostumeCorePredicate(display_name_en='neckline', id='neckline', uri='https://w3id.org/costumeCore/ontology/neckline')
otherMaterials = CostumeCorePredicate(display_name_en='other materials', id='otherMaterials', uri='https://w3id.org/costumeCore/ontology/otherMaterials')
pantsType = CostumeCorePredicate(display_name_en='pants type', id='pantsType', uri='https://w3id.org/costumeCore/ontology/pantsType')
pattern = CostumeCorePredicate(display_name_en='pattern', id='pattern', uri='https://w3id.org/costumeCore/ontology/pattern')
placeOfRepository = CostumeCorePredicate(display_name_en='holding institution', id='placeOfRepository', uri='http://purl.org/vra/placeOfRepository')
privateInformation = CostumeCorePredicate(display_name_en='private information', id='privateInformation', uri='https://w3id.org/costumeCore/ontology/privateInformation')
publicInformation = CostumeCorePredicate(display_name_en='public information', id='publicInformation', uri='https://w3id.org/costumeCore/ontology/publicInformation')
relation = CostumeCorePredicate(display_name_en='relation', id='relation', uri='http://purl.org/dc/terms/relation')
rights = CostumeCorePredicate(display_name_en='rights', id='rights', uri='http://purl.org/dc/terms/rights')
rightsHolder = CostumeCorePredicate(display_name_en='rights holder', id='rightsHolder', uri='http://purl.org/dc/terms/rightsHolder')
robeType = CostumeCorePredicate(display_name_en='robe type', id='robeType', uri='https://w3id.org/costumeCore/ontology/robeType')
shortsType = CostumeCorePredicate(display_name_en='shorts type', id='shortsType', uri='https://w3id.org/costumeCore/ontology/shortsType')
silhouette = CostumeCorePredicate(display_name_en='silhouette', id='silhouette', uri='https://w3id.org/costumeCore/ontology/silhouette')
size = CostumeCorePredicate(display_name_en='size', id='size', uri='https://w3id.org/costumeCore/ontology/size')
skirtType = CostumeCorePredicate(display_name_en='skirt type', id='skirtType', uri='https://w3id.org/costumeCore/ontology/skirtType')
sleeveLength = CostumeCorePredicate(display_name_en='sleeve length', id='sleeveLength', uri='https://w3id.org/costumeCore/ontology/sleeveLength')
sleeveType = CostumeCorePredicate(display_name_en='sleeve type', id='sleeveType', uri='https://w3id.org/costumeCore/ontology/sleeveType')
socioEconomicClass = CostumeCorePredicate(display_name_en='socio-economic class', id='socioEconomicClass', uri='https://w3id.org/costumeCore/ontology/socioEconomicClass')
spatial = CostumeCorePredicate(display_name_en='region', id='spatial', uri='http://purl.org/dc/terms/spatial')
startDate = CostumeCorePredicate(display_name_en='date earliest', id='startDate', uri='http://purl.org/vra/startDate')
storageLocation = CostumeCorePredicate(display_name_en='storage location', id='storageLocation', uri='https://w3id.org/costumeCore/ontology/storageLocation')
subject = CostumeCorePredicate(display_name_en='subject', id='subject', uri='http://purl.org/dc/terms/subject')
temporal = CostumeCorePredicate(display_name_en='style period', id='temporal', uri='http://purl.org/dc/terms/temporal')
textileMaterials = CostumeCorePredicate(display_name_en='textile materials', id='textileMaterials', uri='https://w3id.org/costumeCore/ontology/textile')
title = CostumeCorePredicate(display_name_en='title', id='title', uri='http://purl.org/dc/terms/title')
topType = CostumeCorePredicate(display_name_en='top type', id='topType', uri='https://w3id.org/costumeCore/ontology/topType')
treatment = CostumeCorePredicate(display_name_en='treatment', id='treatment', uri='https://w3id.org/costumeCore/ontology/treatment')
trimming = CostumeCorePredicate(display_name_en='trimming', id='trimming', uri='https://w3id.org/costumeCore/ontology/trimming')
type = CostumeCorePredicate(display_name_en='type', id='type', uri='http://purl.org/dc/terms/type')
underarmToWaistIn = CostumeCorePredicate(display_name_en='underarm to waist', id='underarmToWaistIn', uri='https://w3id.org/costumeCore/ontology/underarmToWaistIn')
underwearType = CostumeCorePredicate(display_name_en='underwear type', id='underwearType', uri='https://w3id.org/costumeCore/ontology/underwearType')
waistIn = CostumeCorePredicate(display_name_en='waist', id='waistIn', uri='https://w3id.org/costumeCore/ontology/waistIn')
waistline = CostumeCorePredicate(display_name_en='waistline', id='waistline', uri='https://w3id.org/costumeCore/ontology/waistline')
weave = CostumeCorePredicate(display_name_en='weave', id='weave', uri='https://w3id.org/costumeCore/ontology/weave')
workType = CostumeCorePredicate(display_name_en='work type', id='workType', uri='https://w3id.org/costumeCore/ontology/workType')
wornBy = CostumeCorePredicate(display_name_en='worn by', id='wornBy', uri='http://www.wikidata.org/entity/P7376')
COSTUME_CORE_PREDICATES = (ICOMtype, accessoryType, alternative, cataloguerWithDate, cbLengthIn, cfLengthIn, chestIn, classification, closure, closurePlacement, coatType, collar, colorMain, colorSecondary, condition, conditionDescription, costOriginal, costumeComponents, creator, culturalContext, date, description, dimensionsOther, donator, dressType, endDate, exhibitions, extent, fiber, function, gender, hasInscription, hasTechnique, hemCircumferenceIn, hipsIn, identifier, isReferencedBy, jacketType, length, lifeStages, liturgicalType, mannequin, material, neckline, otherMaterials, pantsType, pattern, placeOfRepository, privateInformation, publicInformation, relation, rights, rightsHolder, robeType, shortsType, silhouette, size, skirtType, sleeveLength, sleeveType, socioEconomicClass, spatial, startDate, storageLocation, subject, temporal, textileMaterials, title, topType, treatment, trimming, type, underarmToWaistIn, underwearType, waistIn, waistline, weave, workType, wornBy)
