from .costume_core_predicate import CostumeCorePredicate

classification = CostumeCorePredicate(display_name_en='''classification''', id='classification', uri='https://w3id.org/costumeCore/ontology/classification')
closure = CostumeCorePredicate(display_name_en='''closure''', id='closure', uri='https://w3id.org/costumeCore/ontology/closure')
closurePlacement = CostumeCorePredicate(display_name_en='''closure placement''', id='closurePlacement', uri='https://w3id.org/costumeCore/ontology/closurePlacement')
collar = CostumeCorePredicate(display_name_en='''collar''', id='collar', uri='https://w3id.org/costumeCore/ontology/collar')
color = CostumeCorePredicate(display_name_en='''color''', id='color', uri='https://w3id.org/costumeCore/ontology/color')
condition = CostumeCorePredicate(display_name_en='''condition''', id='condition', uri='https://w3id.org/costumeCore/ontology/condition')
costumeComponents = CostumeCorePredicate(display_name_en='''costume components''', id='costumeComponents', uri='https://w3id.org/costumeCore/ontology/costumeComponents')
culture = CostumeCorePredicate(display_name_en='''culture''', id='culture', uri='http://purl.org/vra/culturalContext')
DCMItype = CostumeCorePredicate(display_name_en='''DCMI type''', id='DCMItype', uri='http://purl.org/dc/terms/type')
dressType = CostumeCorePredicate(display_name_en='''dress type''', id='dressType', uri='https://w3id.org/costumeCore/ontology/dressType')
function = CostumeCorePredicate(display_name_en='''function''', id='function', uri='https://w3id.org/costumeCore/ontology/function')
gender = CostumeCorePredicate(display_name_en='''gender''', id='gender', uri='https://w3id.org/costumeCore/ontology/gender')
grain = CostumeCorePredicate(display_name_en='''grain''', id='grain', uri='https://w3id.org/costumeCore/ontology/grain')
ICOMtype = CostumeCorePredicate(display_name_en='''ICOM type''', id='ICOMtype', uri='https://w3id.org/costumeCore/ontology/ICOMType')
lifeStages = CostumeCorePredicate(display_name_en='''life stages''', id='lifeStages', uri='https://w3id.org/costumeCore/ontology/lifeStages')
liturgicalType = CostumeCorePredicate(display_name_en='''liturgical type''', id='liturgicalType', uri='https://w3id.org/costumeCore/ontology/liturgicalType')
material = CostumeCorePredicate(display_name_en='''material''', id='material', uri='http://purl.org/vra/material')
neckline = CostumeCorePredicate(display_name_en='''neckline''', id='neckline', uri='https://w3id.org/costumeCore/ontology/neckline')
pantsType = CostumeCorePredicate(display_name_en='''pants type''', id='pantsType', uri='https://w3id.org/costumeCore/ontology/pantsType')
pattern = CostumeCorePredicate(display_name_en='''pattern''', id='pattern', uri='https://w3id.org/costumeCore/ontology/pattern')
period = CostumeCorePredicate(display_name_en='''period''', id='period', uri='http://purl.org/dc/terms/temporal')
region = CostumeCorePredicate(display_name_en='''region''', id='region', uri='http://purl.org/dc/terms/spatial')
silhouette = CostumeCorePredicate(display_name_en='''silhouette''', id='silhouette', uri='https://w3id.org/costumeCore/ontology/silhouette')
skirtLength = CostumeCorePredicate(display_name_en='''skirt length''', id='skirtLength', uri='https://w3id.org/costumeCore/ontology/skirtLength')
skirtType = CostumeCorePredicate(display_name_en='''skirt type''', id='skirtType', uri='https://w3id.org/costumeCore/ontology/skirtType')
sleeveLength = CostumeCorePredicate(display_name_en='''sleeve length''', id='sleeveLength', uri='https://w3id.org/costumeCore/ontology/sleeveLength')
sleeveType = CostumeCorePredicate(display_name_en='''sleeve type''', id='sleeveType', uri='https://w3id.org/costumeCore/ontology/sleeveType')
socioEconomicClass = CostumeCorePredicate(display_name_en='''socio-economic class''', id='socioEconomicClass', uri='https://w3id.org/costumeCore/ontology/socioEconomicClass')
subject = CostumeCorePredicate(display_name_en='''subject''', id='subject', uri='http://purl.org/dc/terms/subject')
technique = CostumeCorePredicate(display_name_en='''technique''', id='technique', uri='http://purl.org/vra/hasTechnique')
waistline = CostumeCorePredicate(display_name_en='''waistline''', id='waistline', uri='https://w3id.org/costumeCore/ontology/waistline')
workType = CostumeCorePredicate(display_name_en='''work type''', id='workType', uri='https://w3id.org/costumeCore/ontology/workType')
COSTUME_CORE_PREDICATES = (classification, closure, closurePlacement, collar, color, condition, costumeComponents, culture, DCMItype, dressType, function, gender, grain, ICOMtype, lifeStages, liturgicalType, material, neckline, pantsType, pattern, period, region, silhouette, skirtLength, skirtType, sleeveLength, sleeveType, socioEconomicClass, subject, technique, waistline, workType)
