from .costume_core_predicate import CostumeCorePredicate

cataloguerWithDate = CostumeCorePredicate(display_name_en='cataloguer with date', id='cataloguerWithDate', uri='https://w3id.org/costumeCore/ontology/cataloguerWithDate')
cbLengthIn = CostumeCorePredicate(display_name_en='center back length', id='cbLengthIn', uri='https://w3id.org/costumeCore/ontology/cbLengthIn')
cfLengthIn = CostumeCorePredicate(display_name_en='center front length', id='cfLengthIn', uri='https://w3id.org/costumeCore/ontology/cfLengthIn')
chestIn = CostumeCorePredicate(display_name_en='chest', id='chestIn', uri='https://w3id.org/costumeCore/ontology/chestIn')
classification = CostumeCorePredicate(display_name_en='classification', id='classification', uri='https://w3id.org/costumeCore/ontology/classification')
closure = CostumeCorePredicate(display_name_en='closure', id='closure', uri='https://w3id.org/costumeCore/ontology/closure')
closurePlacement = CostumeCorePredicate(display_name_en='closure placement', id='closurePlacement', uri='https://w3id.org/costumeCore/ontology/closurePlacement')
collar = CostumeCorePredicate(display_name_en='collar', id='collar', uri='https://w3id.org/costumeCore/ontology/collar')
colorMain = CostumeCorePredicate(display_name_en='color main', id='colorMain', uri='https://w3id.org/costumeCore/ontology/colorMain')
colorSecondary = CostumeCorePredicate(display_name_en='color secondary', id='colorSecondary', uri='https://w3id.org/costumeCore/ontology/colorSecondary')
condition = CostumeCorePredicate(display_name_en='condition', id='condition', uri='https://w3id.org/costumeCore/ontology/condition')
conditionDescription = CostumeCorePredicate(display_name_en='condition description', id='conditionDescription', uri='https://w3id.org/costumeCore/ontology/conditionDescription')
costOriginal = CostumeCorePredicate(display_name_en='cost original', id='costOriginal', uri='https://w3id.org/costumeCore/ontology/costOriginal')
costumeComponents = CostumeCorePredicate(display_name_en='costume components', id='costumeComponents', uri='https://w3id.org/costumeCore/ontology/costumeComponents')
dimensionsOther = CostumeCorePredicate(display_name_en='measurements other', id='dimensionsOther', uri='https://w3id.org/costumeCore/ontology/dimensionsOther')
dressType = CostumeCorePredicate(display_name_en='dress type', id='dressType', uri='https://w3id.org/costumeCore/ontology/dressType')
exhibitions = CostumeCorePredicate(display_name_en='exhibitions', id='exhibitions', uri='https://w3id.org/costumeCore/ontology/exhibitions')
fiber = CostumeCorePredicate(display_name_en='fiber', id='fiber', uri='https://w3id.org/costumeCore/ontology/fiber')
function = CostumeCorePredicate(display_name_en='function', id='function', uri='https://w3id.org/costumeCore/ontology/function')
gender = CostumeCorePredicate(display_name_en='gender', id='gender', uri='https://w3id.org/costumeCore/ontology/gender')
hemCircumferenceIn = CostumeCorePredicate(display_name_en='hem circumference', id='hemCircumferenceIn', uri='https://w3id.org/costumeCore/ontology/hemCircumferenceIn')
hipsIn = CostumeCorePredicate(display_name_en='hips', id='hipsIn', uri='https://w3id.org/costumeCore/ontology/hipsIn')
icomType = CostumeCorePredicate(display_name_en='ICOM type', id='icomType', uri='https://w3id.org/costumeCore/ontology/icomType')
length = CostumeCorePredicate(display_name_en='length', id='length', uri='https://w3id.org/costumeCore/ontology/length')
lifeStages = CostumeCorePredicate(display_name_en='life stages', id='lifeStages', uri='https://w3id.org/costumeCore/ontology/lifeStages')
liturgicalType = CostumeCorePredicate(display_name_en='liturgical type', id='liturgicalType', uri='https://w3id.org/costumeCore/ontology/liturgicalType')
mannequin = CostumeCorePredicate(display_name_en='mannequin', id='mannequin', uri='https://w3id.org/costumeCore/ontology/mannequin')
neckline = CostumeCorePredicate(display_name_en='neckline', id='neckline', uri='https://w3id.org/costumeCore/ontology/neckline')
otherMaterials = CostumeCorePredicate(display_name_en='other materials', id='otherMaterials', uri='https://w3id.org/costumeCore/ontology/otherMaterials')
pantsType = CostumeCorePredicate(display_name_en='pants type', id='pantsType', uri='https://w3id.org/costumeCore/ontology/pantsType')
pattern = CostumeCorePredicate(display_name_en='pattern', id='pattern', uri='https://w3id.org/costumeCore/ontology/pattern')
privateInformation = CostumeCorePredicate(display_name_en='private information', id='privateInformation', uri='https://w3id.org/costumeCore/ontology/privateInformation')
publicInformation = CostumeCorePredicate(display_name_en='public information', id='publicInformation', uri='https://w3id.org/costumeCore/ontology/publicInformation')
size = CostumeCorePredicate(display_name_en='size', id='size', uri='https://w3id.org/costumeCore/ontology/size')
skirtType = CostumeCorePredicate(display_name_en='skirt type', id='skirtType', uri='https://w3id.org/costumeCore/ontology/skirtType')
sleeveLength = CostumeCorePredicate(display_name_en='sleeve length', id='sleeveLength', uri='https://w3id.org/costumeCore/ontology/sleeveLength')
sleeveType = CostumeCorePredicate(display_name_en='sleeve type', id='sleeveType', uri='https://w3id.org/costumeCore/ontology/sleeveType')
socioEconomicClass = CostumeCorePredicate(display_name_en='socio-economic class', id='socioEconomicClass', uri='https://w3id.org/costumeCore/ontology/socioEconomicClass')
storageLocation = CostumeCorePredicate(display_name_en='storage location', id='storageLocation', uri='https://w3id.org/costumeCore/ontology/storageLocation')
textileMaterials = CostumeCorePredicate(display_name_en='textile materials', id='textileMaterials', uri='https://w3id.org/costumeCore/ontology/textileMaterials')
treatment = CostumeCorePredicate(display_name_en='treatment', id='treatment', uri='https://w3id.org/costumeCore/ontology/treatment')
trimming = CostumeCorePredicate(display_name_en='trimming', id='trimming', uri='https://w3id.org/costumeCore/ontology/trimming')
underarmToWaistIn = CostumeCorePredicate(display_name_en='underarm to waist', id='underarmToWaistIn', uri='https://w3id.org/costumeCore/ontology/underarmToWaistIn')
waistIn = CostumeCorePredicate(display_name_en='waist', id='waistIn', uri='https://w3id.org/costumeCore/ontology/waistIn')
waistline = CostumeCorePredicate(display_name_en='waistline', id='waistline', uri='https://w3id.org/costumeCore/ontology/waistline')
workType = CostumeCorePredicate(display_name_en='work type', id='workType', uri='https://w3id.org/costumeCore/ontology/workType')
wornBy = CostumeCorePredicate(display_name_en='worn by', id='wornBy', uri='https://w3id.org/costumeCore/ontology/wornBy')
COSTUME_CORE_PREDICATES = (cataloguerWithDate, cbLengthIn, cfLengthIn, chestIn, classification, closure, closurePlacement, collar, colorMain, colorSecondary, condition, conditionDescription, costOriginal, costumeComponents, dimensionsOther, dressType, exhibitions, fiber, function, gender, hemCircumferenceIn, hipsIn, icomType, length, lifeStages, liturgicalType, mannequin, neckline, otherMaterials, pantsType, pattern, privateInformation, publicInformation, size, skirtType, sleeveLength, sleeveType, socioEconomicClass, storageLocation, textileMaterials, treatment, trimming, underarmToWaistIn, waistIn, waistline, workType, wornBy)
