COSTUME_CORE_CONTROLLED_VOCABULARIES = {'Age': {'adolescent': None,
         'adult': None,
         'child': None,
         'infant': None,
         'senior': None},
 'Closure Placement': {'center back': None,
                       'center front': None,
                       'double-breasted': None,
                       'neck': None,
                       'off-center back': None,
                       'off-center front': None,
                       'side': None},
 'Closure Type': {'buttons': None,
                  'center back': None,
                  'center front': None,
                  'double-breasted': None,
                  'hooks and eyes': None,
                  'neck': None,
                  'off-center back': None,
                  'off-center front': None,
                  'side': None,
                  'snaps': None,
                  'ties': None,
                  'toggles': None,
                  'velcro': None,
                  'zipper': None},
 'Condition Term': {'excellent': None,
                    'fair': None,
                    'good': None,
                    'poor': None,
                    'very good': None},
 'Function': {'day': None,
              'dinner': None,
              'evening': None,
              'graduation': None,
              'military uniform': None,
              'morning': None,
              'mourning': None,
              'party': None,
              'school uniform': None,
              'sporting': None,
              'wedding': None,
              'work': None,
              'work uniform': None},
 'Gender': {'female': None, 'male': None, 'unisex': None},
 'Main Color': {'beige': None,
                'black': None,
                'blue': None,
                'brown': None,
                'burgundy': None,
                'coral': None,
                'cream': None,
                'fuchsia': None,
                'gold': None,
                'gray': None,
                'green': None,
                'lavender': None,
                'maroon': None,
                'multi': None,
                'navy': None,
                'orange': None,
                'pink': None,
                'purple': None,
                'red': None,
                'rust': None,
                'tan': None,
                'teal': None,
                'turquoise': None,
                'white': None,
                'yellow': None},
 'Material': {'acetate': None,
              'acrylic': None,
              'angora': None,
              'basket weave': None,
              'brocade': None,
              'camel': None,
              'cashmere': None,
              'chiffon': None,
              'cotton': None,
              'crochet': None,
              'damask': None,
              'dobby weave': None,
              'double-weave': None,
              'felt': None,
              'fiber blend': None,
              'georgette': None,
              'glass': None,
              'hemp': None,
              'jacquard': None,
              'knit': None,
              'lace': None,
              'linen': None,
              'looped pile': None,
              'matelasse': None,
              'metal': None,
              'microfiber': None,
              'mohair': None,
              'natural fiber': None,
              'nylon': None,
              'plain weave': None,
              'plastic': None,
              'polyester': None,
              'ramie': None,
              'rayon': None,
              'rib knit': None,
              'rib weave': None,
              'satin weave': None,
              'sheared pile': None,
              'shell': None,
              'silk': None,
              'spandex': None,
              'synthetic fiber': None,
              'taffeta': None,
              'twill weave': None,
              'velvet': None,
              'wood': None,
              'wool': None},
 'Overall Silhouette': {'A-line': None,
                        'Polonaise': None,
                        'S-curve': None,
                        'bias-cut': None,
                        'bustle': None,
                        'chemise': None,
                        'coat': None,
                        'crinoline': None,
                        'drop-waist': None,
                        'empire': None,
                        'fit and flare': None,
                        'hourglass': None,
                        'jumper': None,
                        'mantua': None,
                        'pinafore': None,
                        'princess': None,
                        "robe a l'Anglaise": None,
                        'robe a la Francaise / Watteau back': None,
                        'round gown': None,
                        'sheath': None,
                        'shirtwaist': None,
                        'slip': None,
                        'tent / trapeze': None,
                        'toga': None,
                        'tunic': None,
                        'wrap': None},
 'Record Type': {'collection': None, 'image': None, 'work': None},
 'Secondary Color': {'beige': None,
                     'black': None,
                     'blue': None,
                     'brown': None,
                     'burgundy': None,
                     'coral': None,
                     'cream': None,
                     'fuchsia': None,
                     'gold': None,
                     'gray': None,
                     'green': None,
                     'lavender': None,
                     'maroon': None,
                     'multi': None,
                     'navy': None,
                     'orange': None,
                     'pink': None,
                     'purple': None,
                     'red': None,
                     'rust': None,
                     'tan': None,
                     'teal': None,
                     'turquoise': None,
                     'white': None,
                     'yellow': None},
 'Shawl Border Type': {'complex': None,
                       'contained': None,
                       'long fringe': None,
                       'narrow': None,
                       'short fringe': None,
                       'wide': None},
 'Shawl Design Features': {'ABAB repeat': None,
                           'assymetrical motifs': None,
                           'bi-lateral symmetry': None,
                           'central circle': None,
                           'moon': None,
                           'sprigs': None,
                           'straight botehs': None,
                           'symmetrical motifs': None,
                           'tilting botehs': None},
 'Shawl Shape': {'long': None,
                 'semi-circle': None,
                 'square': None,
                 'triangular': None},
 'Socio-Economic Class': {'OR:': None,
                          'elite': None,
                          'high': None,
                          'low': None,
                          'lower middle': None,
                          'middle': None,
                          'poor': None,
                          'slave': None,
                          'upper middle': None,
                          'working': None},
 'Structure Cut': {'bias': None,
                   'straight': None,
                   'straight (crosswise grain)': None,
                   'straight (lengthwise grain)': None},
 'Structure Hem': {'above knee': None,
                   'ankle': None,
                   'asymmetrical': None,
                   'floor': None,
                   'flounced': None,
                   'hip': None,
                   'knee': None,
                   'maxi': None,
                   'mid calf': None,
                   'mid-thigh': None,
                   'midi': None,
                   'ruffled': None,
                   'train': None,
                   'varied': None},
 'Structure Lining': {'attached crinolines': None,
                      'attached ruffles': None,
                      'bodice fully lined': None,
                      'bodice partially lined': None,
                      'boning': None,
                      'pads': None,
                      'pants fully lined': None,
                      'pants partially lined': None,
                      'skirt fully lined': None,
                      'skirt partially lined': None,
                      'waist tape': None},
 'Structure Neckline': {'Chelsea collar': None,
                        'Mandarin / Chinese / cadet collar': None,
                        'Napoleon': None,
                        'Peter Pan collar': None,
                        'Puritan collar': None,
                        'Queen Anne / high collar': None,
                        'ascot collar': None,
                        'band collar': None,
                        'bateau / boat': None,
                        'bertha collar': None,
                        'bow collar': None,
                        'convertible collar': None,
                        'cowl': None,
                        'crew': None,
                        'funnel collar': None,
                        'gathered collar': None,
                        'halter': None,
                        'henley': None,
                        'hood': None,
                        'inset': None,
                        'jabot collar': None,
                        'jewel': None,
                        'keyhole': None,
                        'layered': None,
                        'off the shoulder': None,
                        'peaked lapel collar': None,
                        'polo collar': None,
                        'portrait collar': None,
                        'round': None,
                        'ruffled collar': None,
                        'sailor / middy collar': None,
                        'scoop': None,
                        'shawl collar': None,
                        'square': None,
                        'strapless': None,
                        'sweetheart': None,
                        'turtleneck collar': None,
                        'v-neck': None,
                        'wingtip collar': None},
 'Structure Pants': {'Bermuda': None,
                     'Jamaica': None,
                     'ankle': None,
                     'briefs': None,
                     'capri': None,
                     'flared': None,
                     'harem': None,
                     'knickers': None,
                     'palazzo': None,
                     'pedal-pusher': None,
                     'short-shorts / hot pants': None,
                     'shorts': None,
                     'toreador': None},
 'Structure Skirt': {'a-line': None,
                     'accordion pleated': None,
                     'balloon': None,
                     'box-pleated': None,
                     'bustle': None,
                     'circular': None,
                     'crinoline': None,
                     'dirndl': None,
                     'flared': None,
                     'flounced': None,
                     'gathered': None,
                     'handkerchief': None,
                     'layered': None,
                     'no seam at center back': None,
                     'peg-top': None,
                     'pegged/tapered': None,
                     'peplum': None,
                     'prairie': None,
                     'sarong': None,
                     'seam at center back': None,
                     'straight': None,
                     'swagged': None,
                     'tiered': None,
                     'trumpet': None,
                     'yoked': None},
 'Structure Sleeve Length': {'camisole straps': None,
                             'cap': None,
                             'elbow': None,
                             'extra long': None,
                             'hanging': None,
                             'long': None,
                             'short': None,
                             'strapless': None,
                             'tank': None,
                             'three-quarter': None},
 'Structure Sleeves': {'2-piece tailored': None,
                       'Juliet': None,
                       'batwing': None,
                       'bell': None,
                       'bishop': None,
                       'block/straight': None,
                       'camisole straps': None,
                       'cap': None,
                       'cowl': None,
                       'criss-cross straps': None,
                       'dolman': None,
                       'elbow dart': None,
                       'elbow gathers': None,
                       'elbow length': None,
                       'extra long': None,
                       'fitted': None,
                       'hanging': None,
                       'kimono': None,
                       'lantern': None,
                       'layered': None,
                       'leg-o-mutton': None,
                       'long': None,
                       'petal': None,
                       'puff': None,
                       'racerback straps': None,
                       'raglan': None,
                       'roll-up': None,
                       'sections/panes': None,
                       'shirt': None,
                       'short': None,
                       'spaghetti/camisole straps': None,
                       'strapless': None,
                       'tank': None,
                       'three-quarter length': None,
                       'wide straps': None},
 'Structure Torso': {'1 dart': None,
                     '2 darts': None,
                     '3 darts': None,
                     '4 darts': None,
                     '5 darts': None,
                     '6 darts': None,
                     '7 or more darts': None,
                     'back yoke': None,
                     'back yoke with gathers': None,
                     'bloused front (pigeon breast)': None,
                     'bust darts': None,
                     'front yoke': None,
                     'front yoke with gathers': None,
                     'gathered': None,
                     'no darts/seams': None,
                     'other darts': None,
                     'other pleats': None,
                     'other seams': None,
                     'princess seams': None,
                     'shoulder darts': None,
                     'shoulder pleats': None,
                     'side seams only': None,
                     'topless': None,
                     'trapeze': None,
                     'waist darts-front': None,
                     'waist pleats': None,
                     'waist-darts-back': None,
                     'wrap': None,
                     'yoke': None,
                     'yoke with gathers': None},
 'Structure Waist': {'Empire / under bust': None,
                     'angled to side': None,
                     'asymmetrical': None,
                     'bare midriff': None,
                     'basque': None,
                     'bolero': None,
                     'curved': None,
                     'dropped': None,
                     'high': None,
                     'hip-level': None,
                     'natural': None,
                     'no waistline': None,
                     'pointed': None,
                     'straight': None,
                     'wrap': None},
 'Structure Waist Shape': {'angled to side': None,
                           'basque': None,
                           'bolero': None,
                           'curved': None,
                           'no waistline': None,
                           'pointed': None,
                           'straight': None,
                           'wrap': None},
 'Technique': {'applique': None,
               'beading': None,
               'braiding': None,
               'burn-out': None,
               'crocheting': None,
               'drawloom': None,
               'embossing': None,
               'embroidery': None,
               'flocking': None,
               'glazing': None,
               'hand sewing': None,
               'hand weaving': None,
               'knitting': None,
               'lace making': None,
               'machine sewing': None,
               'mercerizing': None,
               'needlepoint': None,
               'painting': None,
               'piecing': None,
               'piping': None,
               'pleating': None,
               'polishing': None,
               'printing': None,
               'quilting': None,
               'ruffling': None,
               'smocking': None,
               'weaving': None}}